DROP TABLE IF EXISTS PREFIX_fmdj_custompacks_product;
DROP TABLE IF EXISTS PREFIX_fmdj_custompacks_optgroup;
DROP TABLE IF EXISTS PREFIX_fmdj_custompacks_component;
DROP TABLE IF EXISTS PREFIX_fmdj_custompacks_customization;
DROP TABLE IF EXISTS PREFIX_fmdj_custompacks_customization_component;